package_assets: always #uncomment to package files in dev

javascripts:
  libs:
    - public/javascripts/libs/prototype.js
    - public/javascripts/libs/effects.js
    - public/javascripts/libs/controls.js
    - public/javascripts/libs/dragdrop.js
    - public/javascripts/libs/rails.js
  all:
    - public/javascripts/application.js
    - public/javascripts/review.js
    - public/javascripts/quiz.js

stylesheets:
  all:
    - public/stylesheets/*.css
